# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dynamic_pricing.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64ynamic_pricing.proto\x12\x0e\x64ynamicpricing\"\'\n\x0ePricingRequest\x12\x15\n\rdemand_factor\x18\x01 \x01(\t\" \n\x0fPricingResponse\x12\r\n\x05price\x18\x01 \x01(\x01\"\x1a\n\x18HistoricalPricingRequest\"6\n\x19HistoricalPricingResponse\x12\x19\n\x11historical_prices\x18\x01 \x03(\x01\x32\xde\x01\n\x15\x44ynamicPricingService\x12V\n\x11GetDynamicPricing\x12\x1e.dynamicpricing.PricingRequest\x1a\x1f.dynamicpricing.PricingResponse\"\x00\x12m\n\x14GetHistoricalPricing\x12(.dynamicpricing.HistoricalPricingRequest\x1a).dynamicpricing.HistoricalPricingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dynamic_pricing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRICINGREQUEST']._serialized_start=41
  _globals['_PRICINGREQUEST']._serialized_end=80
  _globals['_PRICINGRESPONSE']._serialized_start=82
  _globals['_PRICINGRESPONSE']._serialized_end=114
  _globals['_HISTORICALPRICINGREQUEST']._serialized_start=116
  _globals['_HISTORICALPRICINGREQUEST']._serialized_end=142
  _globals['_HISTORICALPRICINGRESPONSE']._serialized_start=144
  _globals['_HISTORICALPRICINGRESPONSE']._serialized_end=198
  _globals['_DYNAMICPRICINGSERVICE']._serialized_start=201
  _globals['_DYNAMICPRICINGSERVICE']._serialized_end=423
# @@protoc_insertion_point(module_scope)
